### R E G I S T E R
POST http://localhost:8081/api/auth/register
Content-Type: application/json

{
  "lastName": "Mukhtarov",
  "firstName": "Sarvar",
  "aboutMe": "I am Sarvar",
  "password": "1234",
  "phoneNumber": "998330030528",
  "interests": ["Education","Language"],
  "birthDay": "2000-10-29",
  "photoId": "4028818885b670bc0185b67228100000",
  "gender": true,
  "language": "uz",
  "lat": 41.31528,
  "lon": 69.28919
}

### L O G I N
POST http://localhost:8081/api/auth/login
Content-Type: application/json

{
  "phoneNumber": "998330030526",
  "password": "1234"
}